services:
  trade:
    build: {target: trade}
    depends_on: [db, collector]
    ports: ["3000:3000"]
    restart: unless-stopped
    environment:
      DB_ENDPOINT: postgresql://user:password@db:5432/trade

  db:
    build: {target: postgres}
    ports: ["5432:5432"]
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: trade

  collector:
    build: {target: collector}
    restart: unless-stopped
